import type { TechnologyCategory } from "@/types/job";
import type { TechnologyCatalogItem } from "@/types/settings";
export interface TechnologyRule {
  name: string;
  category: TechnologyCategory;
  aliases: string[];
  patterns?: RegExp[];
}
const r = (...values: string[]) => values;
export const TECHNOLOGIES: TechnologyRule[] = [
  {
    name: "React",
    category: "frontend",
    aliases: r("react", "react.js", "reactjs"),
  },
  {
    name: "Next.js",
    category: "frontend",
    aliases: r("next.js", "nextjs", "next js"),
  },
  { name: "Vue", category: "frontend", aliases: r("vue", "vue.js", "vuejs") },
  { name: "Nuxt", category: "frontend", aliases: r("nuxt", "nuxt.js") },
  {
    name: "Angular",
    category: "frontend",
    aliases: r("angular", "angular.js"),
  },
  { name: "Svelte", category: "frontend", aliases: r("svelte") },
  { name: "SvelteKit", category: "frontend", aliases: r("sveltekit") },
  { name: "HTML", category: "frontend", aliases: r("html", "html5") },
  { name: "CSS", category: "frontend", aliases: r("css", "css3") },
  { name: "Sass", category: "frontend", aliases: r("sass", "scss") },
  {
    name: "Tailwind CSS",
    category: "frontend",
    aliases: r("tailwind", "tailwind css"),
  },
  { name: "Redux", category: "frontend", aliases: r("redux") },
  { name: "Zustand", category: "frontend", aliases: r("zustand") },
  {
    name: "JavaScript",
    category: "language",
    aliases: r("javascript", "js", "ecmascript"),
  },
  { name: "TypeScript", category: "language", aliases: r("typescript", "ts") },
  { name: "Python", category: "language", aliases: r("python", "python3") },
  {
    name: "Java",
    category: "language",
    aliases: r("java"),
    patterns: [/\bjava\b(?!\s*script)/gi],
  },
  {
    name: "Go",
    category: "language",
    aliases: [],
    patterns: [
      /\bgolang\b/gi,
      /\bgo (?:developer|engineer|programming|language)\b/gi,
      /\bprogramming in go\b/gi,
      /\bexperience (?:with|in) go\b/gi,
    ],
  },
  { name: "Ruby", category: "language", aliases: r("ruby") },
  { name: "PHP", category: "language", aliases: r("php") },
  { name: "C#", category: "language", aliases: r("c#", "c sharp") },
  { name: "Kotlin", category: "language", aliases: r("kotlin") },
  { name: "Scala", category: "language", aliases: r("scala") },
  { name: "Rust", category: "language", aliases: r("rust") },
  { name: "Swift", category: "language", aliases: r("swift") },
  {
    name: "Objective-C",
    category: "language",
    aliases: r("objective-c", "objective c"),
  },
  {
    name: "Node.js",
    category: "backend",
    aliases: r("node.js", "nodejs", "node js"),
  },
  {
    name: "Express",
    category: "backend",
    aliases: r("express.js", "expressjs", "express"),
  },
  { name: "NestJS", category: "backend", aliases: r("nestjs", "nest.js") },
  { name: "Django", category: "backend", aliases: r("django") },
  { name: "Flask", category: "backend", aliases: r("flask") },
  { name: "FastAPI", category: "backend", aliases: r("fastapi", "fast api") },
  {
    name: "Spring",
    category: "backend",
    aliases: r("spring", "spring framework"),
  },
  {
    name: "Spring Boot",
    category: "backend",
    aliases: r("spring boot", "springboot"),
  },
  {
    name: "Ruby on Rails",
    category: "backend",
    aliases: r("ruby on rails", "rails"),
  },
  { name: "Laravel", category: "backend", aliases: r("laravel") },
  { name: ".NET", category: "backend", aliases: r(".net", "dotnet") },
  { name: "ASP.NET", category: "backend", aliases: r("asp.net", "asp net") },
  {
    name: "MongoDB",
    category: "database",
    aliases: r("mongodb", "mongo db", "mongo"),
  },
  {
    name: "PostgreSQL",
    category: "database",
    aliases: r("postgresql", "postgres"),
  },
  { name: "MySQL", category: "database", aliases: r("mysql") },
  { name: "MariaDB", category: "database", aliases: r("mariadb") },
  {
    name: "SQL Server",
    category: "database",
    aliases: r("sql server", "mssql"),
  },
  { name: "Oracle", category: "database", aliases: r("oracle database") },
  { name: "DynamoDB", category: "database", aliases: r("dynamodb") },
  { name: "Redis", category: "database", aliases: r("redis") },
  {
    name: "Elasticsearch",
    category: "database",
    aliases: r("elasticsearch", "elastic search"),
  },
  { name: "Snowflake", category: "database", aliases: r("snowflake") },
  { name: "BigQuery", category: "database", aliases: r("bigquery") },
  { name: "Cassandra", category: "database", aliases: r("cassandra") },
  { name: "SQLite", category: "database", aliases: r("sqlite") },
  { name: "AWS", category: "cloud", aliases: r("aws", "amazon web services") },
  { name: "Azure", category: "cloud", aliases: r("azure", "microsoft azure") },
  {
    name: "Google Cloud",
    category: "cloud",
    aliases: r("google cloud", "gcp"),
  },
  { name: "Docker", category: "devops", aliases: r("docker") },
  { name: "Kubernetes", category: "devops", aliases: r("kubernetes", "k8s") },
  { name: "Terraform", category: "devops", aliases: r("terraform") },
  { name: "Jenkins", category: "devops", aliases: r("jenkins") },
  { name: "GitHub Actions", category: "devops", aliases: r("github actions") },
  { name: "GitLab CI", category: "devops", aliases: r("gitlab ci") },
  { name: "CircleCI", category: "devops", aliases: r("circleci") },
  { name: "Kafka", category: "devops", aliases: r("apache kafka", "kafka") },
  { name: "RabbitMQ", category: "devops", aliases: r("rabbitmq") },
  { name: "Nginx", category: "devops", aliases: r("nginx") },
  { name: "React Native", category: "mobile", aliases: r("react native") },
  { name: "Expo", category: "mobile", aliases: r("expo") },
  { name: "Flutter", category: "mobile", aliases: r("flutter") },
  { name: "SwiftUI", category: "mobile", aliases: r("swiftui") },
  { name: "Android", category: "mobile", aliases: r("android") },
  { name: "iOS", category: "mobile", aliases: r("ios") },
  { name: "Jest", category: "testing", aliases: r("jest") },
  { name: "Vitest", category: "testing", aliases: r("vitest") },
  { name: "Cypress", category: "testing", aliases: r("cypress") },
  { name: "Playwright", category: "testing", aliases: r("playwright") },
  { name: "Selenium", category: "testing", aliases: r("selenium") },
  { name: "Pytest", category: "testing", aliases: r("pytest") },
  { name: "JUnit", category: "testing", aliases: r("junit") },
  { name: "Mocha", category: "testing", aliases: r("mocha") },
  {
    name: "REST API",
    category: "architecture",
    aliases: r("rest api", "restful api", "restful services"),
  },
  { name: "GraphQL", category: "architecture", aliases: r("graphql") },
  {
    name: "Microservices",
    category: "architecture",
    aliases: r("microservices", "micro-services"),
  },
  { name: "Serverless", category: "architecture", aliases: r("serverless") },
  {
    name: "Event-driven architecture",
    category: "architecture",
    aliases: r("event-driven architecture", "event driven architecture"),
  },
  {
    name: "WebSockets",
    category: "architecture",
    aliases: r("websockets", "websocket"),
  },
  { name: "gRPC", category: "architecture", aliases: r("grpc") },
  {
    name: "CI/CD",
    category: "architecture",
    aliases: r("ci/cd", "continuous integration"),
  },
  {
    name: "Machine learning",
    category: "architecture",
    aliases: r("machine learning"),
  },
  {
    name: "LLM",
    category: "architecture",
    aliases: r("llm", "large language model"),
  },
  {
    name: "RAG",
    category: "architecture",
    aliases: r("retrieval augmented generation", "rag"),
  },
  { name: "Vite", category: "frontend", aliases: r("vite", "vite.js") },
  { name: "Webpack", category: "frontend", aliases: r("webpack") },
  { name: "Storybook", category: "frontend", aliases: r("storybook") },
  { name: "Bootstrap", category: "frontend", aliases: r("bootstrap") },
  {
    name: "Material UI",
    category: "frontend",
    aliases: r("material ui", "mui"),
  },
  { name: "jQuery", category: "frontend", aliases: r("jquery") },
  { name: "SQL", category: "language", aliases: r("sql") },
  { name: "C++", category: "language", aliases: r("c++", "cpp") },
  { name: "Dart", category: "language", aliases: r("dart") },
  { name: "Bash", category: "language", aliases: r("bash", "shell scripting") },
  { name: "PowerShell", category: "language", aliases: r("powershell") },
  {
    name: "C",
    category: "language",
    aliases: [],
    patterns: [
      /\bc programming\b/gi,
      /\bprogramming in c\b/gi,
      /\bexperience (?:with|in) c\b/gi,
    ],
  },
  {
    name: "R",
    category: "language",
    aliases: [],
    patterns: [
      /\br programming\b/gi,
      /\bprogramming in r\b/gi,
      /\bexperience (?:with|in) r\b/gi,
    ],
  },
  { name: "Fastify", category: "backend", aliases: r("fastify") },
  { name: "Koa", category: "backend", aliases: r("koa", "koa.js") },
  { name: "Prisma", category: "backend", aliases: r("prisma", "prisma orm") },
  { name: "Hibernate", category: "backend", aliases: r("hibernate") },
  {
    name: "Entity Framework",
    category: "backend",
    aliases: r("entity framework", "ef core"),
  },
  {
    name: "Firebase",
    category: "database",
    aliases: r("firebase", "firestore"),
  },
  { name: "Supabase", category: "database", aliases: r("supabase") },
  {
    name: "CockroachDB",
    category: "database",
    aliases: r("cockroachdb", "cockroach db"),
  },
  { name: "Neo4j", category: "database", aliases: r("neo4j") },
  { name: "Pinecone", category: "database", aliases: r("pinecone") },
  { name: "Weaviate", category: "database", aliases: r("weaviate") },
  {
    name: "Vector database",
    category: "database",
    aliases: r("vector database", "vector db"),
  },
  { name: "Cloudflare", category: "cloud", aliases: r("cloudflare") },
  { name: "Vercel", category: "cloud", aliases: r("vercel") },
  { name: "Heroku", category: "cloud", aliases: r("heroku") },
  {
    name: "DigitalOcean",
    category: "cloud",
    aliases: r("digitalocean", "digital ocean"),
  },
  { name: "Git", category: "devops", aliases: r("git") },
  { name: "GitHub", category: "devops", aliases: r("github") },
  { name: "GitLab", category: "devops", aliases: r("gitlab") },
  { name: "Bitbucket", category: "devops", aliases: r("bitbucket") },
  { name: "Linux", category: "devops", aliases: r("linux") },
  { name: "Unix", category: "devops", aliases: r("unix") },
  { name: "Helm", category: "devops", aliases: r("helm", "helm charts") },
  { name: "Ansible", category: "devops", aliases: r("ansible") },
  { name: "Pulumi", category: "devops", aliases: r("pulumi") },
  { name: "OpenShift", category: "devops", aliases: r("openshift") },
  { name: "Argo CD", category: "devops", aliases: r("argo cd", "argocd") },
  { name: "Prometheus", category: "devops", aliases: r("prometheus") },
  { name: "Grafana", category: "devops", aliases: r("grafana") },
  { name: "Datadog", category: "devops", aliases: r("datadog") },
  { name: "New Relic", category: "devops", aliases: r("new relic") },
  { name: "Sentry", category: "devops", aliases: r("sentry") },
  {
    name: "HashiCorp Vault",
    category: "devops",
    aliases: r("hashicorp vault", "vault"),
  },
  {
    name: "Testing Library",
    category: "testing",
    aliases: r("testing library", "react testing library"),
  },
  { name: "Puppeteer", category: "testing", aliases: r("puppeteer") },
  { name: "RSpec", category: "testing", aliases: r("rspec") },
  {
    name: "AI",
    category: "architecture",
    aliases: r("ai", "artificial intelligence", "generative ai", "genai"),
  },
  { name: "OpenAI", category: "architecture", aliases: r("openai", "open ai") },
  { name: "LangChain", category: "architecture", aliases: r("langchain") },
  { name: "TensorFlow", category: "architecture", aliases: r("tensorflow") },
  { name: "PyTorch", category: "architecture", aliases: r("pytorch") },
  {
    name: "scikit-learn",
    category: "architecture",
    aliases: r("scikit-learn", "sklearn"),
  },
  { name: "NumPy", category: "architecture", aliases: r("numpy") },
  { name: "pandas", category: "architecture", aliases: r("pandas") },
  {
    name: "Hugging Face",
    category: "architecture",
    aliases: r("hugging face", "huggingface"),
  },
  { name: "MLflow", category: "architecture", aliases: r("mlflow") },
  {
    name: "NLP",
    category: "architecture",
    aliases: r("nlp", "natural language processing"),
  },
  {
    name: "Computer vision",
    category: "architecture",
    aliases: r("computer vision"),
  },
  {
    name: "OAuth",
    category: "architecture",
    aliases: r("oauth", "oauth2", "oauth 2.0"),
  },
  {
    name: "JWT",
    category: "architecture",
    aliases: r("jwt", "json web token"),
  },
  {
    name: "SSO",
    category: "architecture",
    aliases: r("sso", "single sign-on", "single sign on"),
  },
  {
    name: "SOAP",
    category: "architecture",
    aliases: r("soap api", "soap services"),
  },
  { name: "Agile", category: "other", aliases: r("agile") },
  { name: "Scrum", category: "other", aliases: r("scrum") },
];
export function canonicalTechnology(value: string): string {
  const lower = value.trim().toLowerCase();
  return (
    TECHNOLOGIES.find(
      (t) =>
        t.name.toLowerCase() === lower ||
        t.aliases.some((a) => a.toLowerCase() === lower),
    )?.name ?? value.trim()
  );
}

export const DEFAULT_TECHNOLOGY_CATALOG: TechnologyCatalogItem[] =
  TECHNOLOGIES.map((technology) => ({
    name: technology.name,
    category: technology.category,
    aliases: [...technology.aliases],
    ...(technology.patterns?.length
      ? { patterns: technology.patterns.map((pattern) => pattern.source) }
      : {}),
  }));
