import * as cheerio from "cheerio";
import type { ScrapedJob } from "@/types/scraping";
import { cleanDescriptionText,remoteFromText,sourceFromUrl } from "./text-utils";
import { sanitizeJobHtml } from "./sanitize-html";
type JsonObject=Record<string,unknown>;
const obj=(v:unknown):v is JsonObject=>typeof v==="object"&&v!==null&&!Array.isArray(v);
function flatten(v:unknown):JsonObject[]{if(Array.isArray(v))return v.flatMap(flatten);if(!obj(v))return[];return [v,...flatten(v["@graph"])];}
function stringValue(v:unknown):string|null{return typeof v==="string"&&v.trim()?v.trim():null;}
function nameOf(v:unknown):string|null{return obj(v)?stringValue(v.name):stringValue(v);}
function locationOf(v:unknown):string|null{const item=Array.isArray(v)?v[0]:v;if(!obj(item))return null;const address=obj(item.address)?item.address:item;return [address.addressLocality,address.addressRegion,address.addressCountry].map(nameOf).filter(Boolean).join(", ")||nameOf(item);}
function salaryOf(v:unknown):string|null{if(!obj(v))return stringValue(v);const currency=stringValue(v.currency);const val=obj(v.value)?v.value:v;const min=stringValue(val.minValue)??(typeof val.minValue==="number"?String(val.minValue):null);const max=stringValue(val.maxValue)??(typeof val.maxValue==="number"?String(val.maxValue):null);const unit=stringValue(val.unitText);return [currency,min&&max?`${min}–${max}`:min??max,unit?`per ${unit.toLowerCase()}`:null].filter(Boolean).join(" ")||null;}
export function extractJsonLd(html:string,base:{url:string;normalizedUrl:string;finalUrl:string}):ScrapedJob|null{const $=cheerio.load(html);for(const node of $("script[type='application/ld+json']").toArray()){try{const raw=$(node).html()?.trim();if(!raw)continue;for(const item of flatten(JSON.parse(raw))){const types=Array.isArray(item["@type"])?item["@type"]:[item["@type"]];if(!types.some(t=>String(t).toLowerCase()==="jobposting"))continue;const description=stringValue(item.description)??"";const descriptionHtml=sanitizeJobHtml(description);const location=locationOf(item.jobLocation);const remoteText=[item.jobLocationType,item.applicantLocationRequirements,location,description].map(v=>typeof v==="string"?v:JSON.stringify(v??"")).join(" ");return{...base,source:sourceFromUrl(base.finalUrl),title:stringValue(item.title),company:nameOf(item.hiringOrganization),location,remoteStatus:remoteFromText(remoteText),employmentType:Array.isArray(item.employmentType)?item.employmentType.join(", "):stringValue(item.employmentType),salary:salaryOf(item.baseSalary),descriptionText:cleanDescriptionText(description),descriptionHtml,datePosted:stringValue(item.datePosted),validThrough:stringValue(item.validThrough),scrapingMethod:"json-ld"};}}catch{continue;}}return null;}
